---
title: "Sampling Distributions"
format:
  revealjs:
    navigation-mode: vertical
    controls-layout: bottom-right
    controls-tutorial: true
    incremental: false 
    chalkboard:
      src: notes/4b.json
      theme: whiteboard
      chalk-width: 4

revealjs-plugins:
  - pointer
  - verticator
  
filters: 
  - reveal-header
  - code-fullscreen
  - reveal-auto-agenda

editor: source
---

```{r}
#| include: false

knitr::opts_chunk$set(echo = T)

```

# Statistics

## Sample

When collecting data to construct a sample, the sample is a collection of random variables.

::: fragment
Therefore, the sample can be subjected to probability properties.
:::

## iid Random Variables

A sample of random variables are said to be iid if they are identical and independentally distributed.

For example, $X$ and $Y$ are iid, if $X$ and $Y$ has the same distribution $f(\theta)$ and $X \perp  Y$

## Statistics

A statistic is a transformation of the the sample data. 

::: fragment
Before data is calculated, a statistic from a sample can take any value.
:::

::: fragment
Therefore, a statistic must be a random variable.
:::

# Sampling Distributions

## Sampling Distributions

A sampling distribution is the distribution of a statistic. Many known statistics have a known distribution.

## $\bar X$

Let $X_1, X_2, \ldots, X_n\overset{iid}{\sim}N(\mu,\sigma^2)$ , show that $\bar X \sim N(\mu,\sigma^2/n)$. Note: the MGF of $X_i$ is $e^{\mu t + \frac{t^2\sigma^2}{2}}$.

## Sum of $\chi^2_1$

Let $Z_1^2, \ldots, Z_n^2$ be a iid $\chi^2_1$. Find $Y = \sum^n_{i=1} Z_i^2$ 

## $s^2$

## t-distribution

Let $Z\sim N(0,1)$, $W\sim \chi^2_\nu$, $Z\perp W$; therefore:

$$
T=\frac{Z}{\sqrt{W/\nu}} \sim t_\nu
$$

## F-distribution

Let $W_1\sim\chi^2_{\nu_1}$ $W_2\sim\chi^2_{\nu_2}$, and $W_1\perp W_2$; therefore:

$$
F = \frac{W_1/\nu_1}{W_2/\nu_2}\sim F_{\nu_1,\nu_2}
$$


# Central Limit Theorem

## Central Limit Theorem

Let $X_1, X_2, \ldots, X_n$ be identical and independent distributed random variables with $E(X_i)=\mu$ and $Var(X_i) = \sigma²$. We define

$$
Y_n = \sqrt n \left(\frac{\bar X-\mu}{\sigma}\right) \mathrm{ where }\ \bar X = x\frac{1}{n}\sum^n_{i=1}X_i.
$$

Then, the distribution of the function $Y_n$ converges to a standard normal distribution function as $n\rightarrow \infty$.

## Central Limit Theorem

$$
\bar X \sim N\left(\mu, \frac{\sigma^2}{n}\right)
$$

## Example

Let $X_1, \ldots, X_n \overset{iid}{\sim} \chi^2_p$, the MGF is $M(t)=(1-2t)^{-p/2}$. Find the distribution of $\bar X$ as $n \rightarrow \infty$.
